### ISSUE TITLE
TypeError: MaxAndArgmax needs a constant axis  +  NameError: global name 'EndOfTraining' is not defined

### ISSUE THREAD

**Issue by andyyuan78** [tariqdaouda/Mariana#3]
ubgpu@ubgpu:~/github/Mariana$ sudo python Mariana/examples/mnist_mlp.py 
Using gpu device 0: GeForce GTX 970

>|\/| /-\ |-> | /-\ |\| /-\>

Run device:
-----------
  I will use the [-GPU-] to run function 'train' of layer 'out'!

  Cheers :),

  Mariana

Run device:
-----------
  I will use the [-GPU-] to run function 'test' of layer 'out'!

  Cheers :),

  Mariana

Run device:
-----------
  I will use the [-GPU-] to run function 'propagate' of layer 'out'!

  Cheers :),

  Mariana

ERROR (theano.gof.opt): Optimization failure due to: local_argmax_pushdown
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1493, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/nnet.py", line 1448, in local_argmax_pushdown
    return tensor._max_and_argmax(pre_x, axis)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 1252, in make_node
    raise TypeError("MaxAndArgmax needs a constant axis")
TypeError: MaxAndArgmax needs a constant axis

ERROR (theano.gof.opt): Optimization failure due to: local_argmax_pushdown
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1493, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/nnet.py", line 1454, in local_argmax_pushdown
    ('x', 0))(pre_bias), axis)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 1252, in make_node
    raise TypeError("MaxAndArgmax needs a constant axis")
TypeError: MaxAndArgmax needs a constant axis

==>rec: ggplot2, commit 1, pid: 14344:
  |-test set
    |->out: 1.62696 +best+
  |-train set
    |->out: 1.96462 +best+
  |-validation set
    |->out: 1.61709 +best+

==>rec: ggplot2, commit 2, pid: 14344:
  |-test set
    |->out: 1.48826 +best+
  |-train set
    |->out: 1.5747 +best+
  |-validation set
    |->out: 1.48133 +best+

==>rec: ggplot2, commit 3, pid: 14344:
  |-test set
    |->out: 1.38383 +best+

********************

==>rec: ggplot2, commit 1001, pid: 14344:
  |-test set
    |->out: 0.119731 +best+
  |-train set
    |->out: 0.0630581 +best+
  |-validation set
    |->out: 0.124834 (best: 0.124825 @ commit: 974)

===
Dying gracefully from NameError, and saving myself to:
...dx-xb_MLP_death_by_NameError_Sat_Jun_13_21:45:02_2015
===
Traceback (most recent call last):
  File "Mariana/examples/mnist_mlp.py", line 74, in <module>
    trainer.start("MLP", mlp)
  File "/home/ubgpu/github/Mariana/Mariana/training/trainers.py", line 195, in start
    Trainer_ABC.start( self, runName, model, recorder, trainingOrder, shuffle, datasetName )
  File "/home/ubgpu/github/Mariana/Mariana/training/trainers.py", line 103, in start
    return self.run(runName, model, recorder, *args, **kwargs)
  File "/home/ubgpu/github/Mariana/Mariana/training/trainers.py", line 340, in run
    raise EndOfTraining(crit)
NameError: global name 'EndOfTraining' is not defined
ubgpu@ubgpu:~/github/Mariana$ git remote -v

**Comment by tariqdaouda** [comment]
Thanks for the issue,
I have corrected the **NameError**, regarding the **TypeError: MaxAndArgmax needs a constant axis**, it seem to be a theano related issue, as I was unable to reproduce it. Could you try to update theano to the latest version (git pull) or print the contents of theano.__version__ if it does not work.

You can do :
```python
  import Mariana.settings as MSET
  MSET.VERBOSE = False
```
To suppress Mariana's friendly messages and keep only the errors.

Cheers,
